### ISSUE TITLE
"Overview" is missing

### ISSUE THREAD

**Issue by roland-KA** [SE-TINF22B2/G1-CashCompass#110]
All links (in README.md as well as the Wiki sidebar) to the "Overview"-document lead to a "create new page"-form. The "Overview"-document itself got somehow lost ... well, it is still somewhere in the depths of Git-memory 🤓 to where you can re-establish the links.

**Comment by roland-KA** [comment]
The link in https://github.com/SE-TINF22B2/G1-CashCompass/wiki/Use-cases still works 😊👍

**Comment by SirSimon04** [comment]
Fixed this. Was due to renaming of big picture to overview which changes the link
