### ISSUE TITLE
Adjust Big Picture

### ISSUE THREAD

**Issue by stefanrudi2004** [SE-TINF22B2/G1-CashCompass#143]
### Description
We have to adjust our big picture and add the `Friends` term. 

### Motivation
In our use cases the term `Friends` arises for the first time. However, it is not explained or even mentioned in the big picture. This was a feedback from Schätzle and should be implemented before the presentation.

**Comment by stefanrudi2004** [comment]
Adapt the whole big picture and add it to the presentation. In this term we have also added the term `Friends`.

**Comment by JJthere** [comment]
Shouldnt this be in [here](https://github.com/SE-TINF22B2/G1-CashCompass/wiki/Overview)?
