### ISSUE TITLE
Implement factories and tests for it

### ISSUE THREAD

**Issue by Gamagu** [SE-TINF22B2/G1-CashCompass#184]
implement factories for each database object.
This includes: 
- active/passive accounts
- categories
- transactions
- recurring transactions

**Comment by mathisi** [comment]
@Gamagu please enhance description on this issue

**Comment by Gamagu** [comment]
Time consumed over three weeks: 13h.  15.4:21.4:9h: 22.4-28.4:4h. 29.4-5.5: 0h
