### ISSUE TITLE
[FAIL] implement class remote storage

### ISSUE THREAD

**Issue by Gamagu** [SE-TINF22B2/G1-CashCompass#190]
### Description
The remote storage is the data adapter for retrieving data from the server, thus it must implement 3 methods with are described in data_adapter.

Make sure to create the branch with a base after the commit where the Initial_data pull types were changed to factories.

The plan is, that this call is responsible for interacting with the server. Because of that in the future, every auth related logic should be implemented or be directed through this class, as well as every friend and stock related request but those entities are not yet supported.

**Comment by SirSimon04** [comment]
done with initial pull, will open new ones for uploading data
