### ISSUE TITLE
[FAIL] Quarry Collection

### ISSUE THREAD

**Issue by Gamagu** [SE-TINF22B2/G1-CashCompass#255]
### Description
What querries does the frontend need?

- Category from id or from accountNr
- List of all transactions of categories

**Comment by stefanrudi2004** [comment]
#86 needs a list of all incomes and expense transactions

**Comment by mathisi** [comment]
#87 needs a list of all transactions of one user sorted by time (latest at first). Necessary fields per transaction: 
- Is Transaction Income or expense
- Amout
- Transaction Label
- Wallet Name
- Category Icon

**Comment by mathisi** [comment]
#95 needs a list of all recurring transactions of one user, no special sorting necessary. Necessary fields per recurring transaction:
- is transaction recurring income or expense?
- amount
- label

**Comment by SirSimon04** [comment]
closed with #290
