### ISSUE TITLE
Search for a stock api

### ISSUE THREAD

**Issue by SirSimon04** [SE-TINF22B2/G1-CashCompass#71]
**Describe the feature**
Search for an api where we can get our stock information from. It should have a search by ISIN and the value of each stock should be requestable at least once a day.

**Comment by SirSimon04** [comment]
## [Polygon.io](https://polygon.io/)
- Free are five api calls per minute 
  - need a scheduler to update all the data
- only end of day data is requestable
- historical data for the last two years

**Comment by SirSimon04** [comment]
## [alphavantage.co](https://www.alphavantage.co/)
- has daily stock values and intraday endpoints
- has a lost of historical data
- but is limited to 25 calls per day
- we asked for academic access which would be unlimited
  - waiting for response

**Comment by roland-KA** [comment]
Wouldn't Yahoo Finance be an alternative, if the above mentioned providers don't work? The YH isn't perfect (see: https://algotrading101.com/learn/yahoo-finance-api-guide/), but for the purpose of this project perhaps sufficient?
