### ISSUE TITLE
think about documentation

### ISSUE THREAD

**Issue by SirSimon04** [SE-TINF22B2/G1-CashCompass#77]
**Describe the feature**
- how to document the frontend, ui components
- how to document the backend and api description
- write everything in the wiki

**Comment by SirSimon04** [comment]
Probably https://typedoc.org/guides/installation/, will be tested in branch

**Comment by SirSimon04** [comment]
Backend doc is described in wiki

**Comment by Gamagu** [comment]
> Backend doc is described in wiki, finish for backend

Bro des war 2 Uhr nachts????
